#基础配置文件，存放公共配置
server:
  port: 8001
spring:
  profiles:
    active: dev
  application:
    #在 yml 中获取 pom.xml 中的配置，需要配置 maven 插件中的资源加载配置 filtering=true 且生效范围为 src/main/resources
    #如果依赖了 spring-boot-starter-parent 工程，则需要用表达式 @value@ 获取，并且加上单引号，maven 会在编译的时候进行替换。
    name: '@project.parent.name@'
    version: '@project.version@'
#moyu框架配置
moyu:
  #方法运行日志切面
  method-time:
    #是否启用
    enabled: true
    #日志切点
    pointcut-expression: execution(* org.moyu.blog..controller..*(..))
    #接口参数截取长度
    paramsMaxLength: 2000
logging:
  #日志输出在工程相对路径下的 logs 文件夹
  file:
    path: ./logs